server:
  port: 9091

security:
  user:
    name: api
    password: api

logging:
  file: logs/application.log

my:
  bucket: io.klerch.alexa.translator
  bucketUrl: https://s3.amazonaws.com/io.klerch.alexa.translator/
